# Configurações para integração fractal no framework ΨQRH
fractal_integration:
  # Método padrão para análise fractal
  default_method: "box_counting"
  
  # Configurações do método de contagem de caixas
  box_counting:
    grid_size: 256
    n_samples: 10000
    min_box_size: 0.001
    max_box_size: 1.0
    n_scales: 20
  
  # Configurações do método espectral
  spectral:
    min_frequency: 1
    max_frequency: 128
    power_law_fit_method: "curve_fit"
  
  # Mapeamento entre dimensão fractal e parâmetro α
  alpha_mapping:
    scaling_factor: 1.0
    dim_type: "1d"  # 1d, 2d, ou 3d
  
  # Configurações de adaptação
  adaptation:
    enabled: true
    analysis_frequency: 100  # Passos entre análises
    alpha_smoothing: 0.9     # Fator de suavização para α
  
  # Configurações de validação
  validation:
    tolerance:
      dimensional: 1e-10
      fractal_analysis: 0.1
      alpha_mapping: 0.1
    test_cases:
      - name: "cantor_set"
        theoretical_dim: 0.63093
        tolerance: 0.05
      - name: "sierpinski_triangle"
        theoretical_dim: 1.58496
        tolerance: 0.1
      - name: "uniform_2d"
        theoretical_dim: 2.0
        tolerance: 0.2

# Configurações de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "fractal_integration.log"