# Book settings
title: 'Reformulating Transformers: The Î¨QRH Framework'
author: 'Klenio Araujo Padilha'

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  thebe: true

repository:
  url: "https://github.com/klenio/reformulating-transformers"
  path_to_book: "e-book"
  branch: "main"
