# ΨQRH HELM Configuration
# ======================
#
# Configuration file for integrating ΨQRH framework with Stanford's
# Holistic Evaluation of Language Models (HELM) framework.
#
# This configuration defines model specifications, evaluation scenarios,
# and ΨQRH-specific parameters for comprehensive benchmarking.

# Model Configuration
model_deployments:
  - name: psiqrh-quaternion-harmonic
    model_name: psiqrh/quaternion-harmonic
    host_organization: local

    # ΨQRH-specific model parameters
    model_spec:
      model_name: psiqrh-quaternion-harmonic
      model_engine: psiqrh
      organization: local

    # Processing parameters
    max_request_length: 2048
    max_tokens: 512
    max_sequence_length: 2048

    # ΨQRH framework parameters
    psiqrh_config:
      embed_dim: 64
      alpha: 1.5
      beta: 0.01
      use_spectral_filtering: true
      use_fractal_analysis: true
      quaternion_precision: "float32"
      energy_conservation_threshold: 0.05

      # Wave equation parameters
      wave_parameters:
        enable_padilha_equation: true
        omega_scaling: 2.0
        k_scaling: 1.0
        spatial_modulation: true

      # Fractal dimension mapping
      fractal_mapping:
        enable_automatic_mapping: true
        euclidean_dimension: 2.0
        lambda_factor: 0.1
        dimension_bounds: [0.5, 3.0]

      # Spectral filtering
      spectral_filter:
        enable_filtering: true
        filter_type: "logarithmic_phase"
        alpha_scaling: true
        frequency_cutoff: null

# Evaluation Scenarios
run_specs:
  # Natural Language Understanding
  - name: psiqrh_mmlu
    scenario_spec:
      class_name: "helm.benchmark.scenarios.mmlu_scenario.MMLUScenario"
      args:
        subject: "all"
    adapter_spec:
      method: "multiple_choice_joint"
      max_train_instances: 5
      max_eval_instances: 100
    model_spec:
      model_name: "psiqrh-quaternion-harmonic"
    metric_specs:
      - class_name: "helm.benchmark.metrics.classification_metrics.ClassificationMetric"
      - class_name: "helm.benchmark.metrics.efficiency_metrics.EfficiencyMetric"

  # Reading Comprehension
  - name: psiqrh_reading_comprehension
    scenario_spec:
      class_name: "helm.benchmark.scenarios.reading_comprehension_scenario.ReadingComprehensionScenario"
      args:
        dataset: "squad"
    adapter_spec:
      method: "generation"
      max_tokens: 100
    model_spec:
      model_name: "psiqrh-quaternion-harmonic"
    metric_specs:
      - class_name: "helm.benchmark.metrics.basic_metrics.BasicMetric"
      - class_name: "helm.benchmark.metrics.efficiency_metrics.EfficiencyMetric"

  # Mathematical Reasoning
  - name: psiqrh_math_reasoning
    scenario_spec:
      class_name: "helm.benchmark.scenarios.math_scenario.MATHScenario"
      args:
        level: "all"
    adapter_spec:
      method: "generation"
      max_tokens: 200
    model_spec:
      model_name: "psiqrh-quaternion-harmonic"
    metric_specs:
      - class_name: "helm.benchmark.metrics.basic_metrics.BasicMetric"
      - class_name: "helm.benchmark.metrics.math_metrics.MathMetric"

  # Code Generation
  - name: psiqrh_code_generation
    scenario_spec:
      class_name: "helm.benchmark.scenarios.code_scenario.HumanEvalScenario"
    adapter_spec:
      method: "generation"
      max_tokens: 300
    model_spec:
      model_name: "psiqrh-quaternion-harmonic"
    metric_specs:
      - class_name: "helm.benchmark.metrics.code_metrics.CodeMetric"
      - class_name: "helm.benchmark.metrics.efficiency_metrics.EfficiencyMetric"

# Metrics Configuration
metrics:
  # Standard HELM metrics
  basic_metrics:
    - "exact_match"
    - "f1_score"
    - "rouge_l"
    - "bleu"

  # ΨQRH-specific metrics
  psiqrh_metrics:
    - name: "energy_conservation"
      description: "Measure of quaternion energy conservation during processing"
      range: [0.0, 2.0]
      optimal: 1.0

    - name: "fractal_coherence"
      description: "Consistency of fractal dimension analysis"
      range: [0.0, 1.0]
      optimal: 1.0

    - name: "quaternion_stability"
      description: "Stability of quaternion norm during processing"
      range: [0.0, 1.0]
      optimal: 1.0

    - name: "spectral_fidelity"
      description: "Fidelity of spectral filtering operations"
      range: [0.0, 1.0]
      optimal: 1.0

    - name: "wave_coherence"
      description: "Coherence of Padilha Wave Equation parameters"
      range: [0.0, 1.0]
      optimal: 1.0

# Evaluation Configuration
evaluation:
  # Output configuration
  output_path: "./helm_results/psiqrh"
  save_detailed_results: true
  save_intermediate_outputs: true

  # Parallel processing
  max_eval_instances: 1000
  num_threads: 4

  # Caching
  cache_dir: "./helm_cache/psiqrh"
  enable_caching: true

  # Logging
  log_level: "INFO"
  log_file: "./logs/psiqrh_helm_evaluation.log"

# Comparison Baselines
baseline_models:
  - name: "gpt-3.5-turbo"
    organization: "openai"

  - name: "claude-3-sonnet"
    organization: "anthropic"

  - name: "llama-2-70b"
    organization: "meta"

  - name: "gemini-pro"
    organization: "google"

# ΨQRH Framework Validation
validation:
  # Mathematical validation
  enable_mathematical_validation: true
  energy_conservation_tolerance: 0.1
  quaternion_norm_tolerance: 0.1

  # Performance validation
  min_processing_speed: 10.0  # tokens per second
  max_memory_usage: 8192      # MB

  # Quality validation
  min_response_quality: 0.7
  enable_coherence_checking: true

  # Error handling
  max_retries: 3
  timeout_seconds: 300
  fallback_mode: "graceful_degradation"

# Experimental Features
experimental:
  # Multi-modal support (future)
  enable_multimodal: false

  # Advanced quaternion operations
  enable_advanced_quaternion_ops: true

  # Real-time fractal analysis
  enable_realtime_fractal_analysis: true

  # Quantum computing preparation
  enable_quantum_preparation: false

  # Hardware acceleration
  enable_gpu_acceleration: true
  enable_mixed_precision: true

# Documentation and Reporting
reporting:
  # Report generation
  generate_pdf_report: true
  generate_json_summary: true
  generate_comparison_charts: true

  # Report sections
  include_sections:
    - "executive_summary"
    - "model_overview"
    - "performance_analysis"
    - "psiqrh_specific_metrics"
    - "comparison_with_baselines"
    - "recommendations"

  # Report customization
  company_logo: null
  report_title: "ΨQRH Framework Evaluation Results"
  report_subtitle: "Quaternion-Harmonic Language Model Assessment"

# Integration Settings
integration:
  # HELM framework version
  helm_version: "latest"

  # API compatibility
  api_version: "v1"
  compatibility_mode: "strict"

  # Custom client configuration
  client_config:
    timeout: 300
    max_retries: 3
    retry_delay: 1.0
    enable_streaming: false

  # Plugin configuration
  plugins:
    - name: "psiqrh_metrics_plugin"
      enabled: true
      config:
        detailed_analysis: true

    - name: "fractal_visualization_plugin"
      enabled: true
      config:
        generate_plots: true
        save_raw_data: true