config_used:
  fractal_integration:
    adaptation:
      alpha_smoothing: 0.9
      analysis_frequency: 100
      enabled: true
    alpha_mapping:
      dim_type: 1d
      scaling_factor: 1.0
    box_counting:
      grid_size: 256
      max_box_size: 1.0
      min_box_size: 0.001
      n_samples: 10000
      n_scales: 20
    default_method: box_counting
    spectral:
      max_frequency: 128
      min_frequency: 1
      power_law_fit_method: curve_fit
    validation:
      test_cases:
      - name: cantor_set
        theoretical_dim: 0.63093
        tolerance: 0.1
      - name: sierpinski_triangle
        theoretical_dim: 1.58496
        tolerance: 0.15
      - name: uniform_2d
        theoretical_dim: 2.0
        tolerance: 0.3
      tolerance:
        alpha_mapping: 0.2
        dimensional: 1e-10
        fractal_analysis: 0.3
  logging:
    file: fractal_integration.log
    format: '%(asctime)s - %(levelname)s - %(message)s'
    level: INFO
detailed_results:
  Component Integration:
    execution_time_ms: 56.5495491027832
    passed: true
  Configuration Compliance:
    execution_time_ms: 1.638174057006836
    passed: true
  Edge Cases & Robustness:
    execution_time_ms: 43.955326080322266
    passed: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApCb29sU3RvcmFn
        ZQpxAVgJAAAAODU5NzAzMjY0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgJAAAAODU5NzAzMjY0
        cQFhLgEAAAAAAAAAAQ==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  Human Chat Simulation:
    execution_time_ms: 15.833854675292969
    passed: false
  Mathematical Consistency:
    execution_time_ms: 3.5026073455810547
    passed: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApCb29sU3RvcmFn
        ZQpxAVgJAAAAODcxNjc0MzUycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgJAAAAODcxNjc0MzUy
        cQFhLgEAAAAAAAAAAQ==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  Performance Benchmarks:
    execution_time_ms: 4127.620458602905
    passed: true
execution_time_s: 4.249911546707153
overall_status: GOOD
passed_tests: 5
performance_metrics:
  fractal_analysis_ms: 7.207393646240234
  qrh_forward_ms: 9.750299453735352
  transformer_forward_ms: 727.2179126739502
success_rate: 0.8333333333333334
timestamp: '2025-09-24 14:12:17'
total_tests: 6
